version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    network_mode: host
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    network_mode: host
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 9042
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_NUM_PARTITIONS: 10
      KAFKA_CREATE_TOPICS: "services:1:1, jobs:40:1, allocated:1:1, complete:1:1, plugins:10:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

