version: '3.4'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    logging:
      driver: none

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.1.147
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_NUM_PARTITIONS: 5
      #KAFKA_CREATE_TOPICS: "services:1:1, jobs:20:1, allocated:1:1, complete:1:1, plugins:1:1"

    logging:
      driver: none

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      
  producer:
    image: blakeasmith/kafka_webscraper_producer
    environment:
            WEBSCRAPER_BOOTSTRAPS: "kafka:9092"
            DELAY_BETWEEN_JOBS: "1000"
            WEBSCRAPER_DEBUG: "false"

  proxy:
    image: blakeasmith/webscraper_proxy_server
    ports:
        - "8080:8080"
    environment:
      WEBSCRAPER_BOOTSTRAPS: "kafka:9092"

  #proxyclient:
    #image: blakeasmith/webscraper_proxy_client
    #environment:
        #PROXY_SERVER: "http://proxy:8080"

  #client:
    #image: blakeasmith/kafka_webscraper_client
    #environment:
      #WEBSCRAPER_BOOTSTRAPS: "kafka:9092"
        
  wordcount_reducer:
    image: blakeasmith/webscraper_reducer_wordcount
    environment:
      WEBSCRAPER_BOOTSTRAPS: "kafka:9092"

