version: '3.4'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    logging:
      driver: none

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.1.147
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "services:1:1, jobs:4:1, allocated:1:1, complete:1:1, plugins:1:1"

    logging:
      driver: none

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      

  provider: 
    image: blakeasmith/kafka_webscraper_provider
    environment:
      WEBSCRAPER_CONFIG: "/config/config.json"
    command: "--jars plugins --services services/services.json"
    volumes: 
      - ./config:/config
      - ./plugins:/plugins
      - ./services:/services


  producer:
    image: blakeasmith/kafka_webscraper_producer
    environment:
      WEBSCRAPER_CONFIG: "/config/config.json"
    volumes: 
      - ./config:/config
    logging:
      driver: none
    depends_on: 
      - provider
    logging:
      driver: none

  client:
    image: blakeasmith/kafka_webscraper_client
    environment:
      WEBSCRAPER_CONFIG: "/config/config.json"
      WAIT_AFTER_HOSTS: 500
      WAIT_HOSTS: "kafka:9092"
    command: sh -c "/wait"
    volumes: 
      - ./config:/config

  #logger: 
    #image: blakeasmith/kafka_webscraper_logger
    #environment:
      #WEBSCRAPER_CONFIG: "/config/config.json"
    #volumes: 
      #- ./config:/config


volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local



