version: '3.4'

services:
  kafka:
    image: spotify/kafka
    logging:
      driver: none
        
  provider: 
    image: blakeasmith/kafka_webscraper_provider
    environment:
      WEBSCRAPER_CONFIG: "/config/config.json"
    command: "--jars plugins --services services/services.json"
    logging:
      driver: none
    volumes: 
      - ./config:/config
      - ./plugins:/plugins
      - ./services:/services

  producer:
    image: blakeasmith/kafka_webscraper_producer
    environment:
      WEBSCRAPER_CONFIG: "/config/config.json"
    logging:
      driver: none
    volumes: 
      - ./config:/config

  client:
    image: blakeasmith/kafka_webscraper_client
    environment:
      WEBSCRAPER_CONFIG: "/config/config.json"
    volumes: 
      - ./config:/config

  logger: 
    image: blakeasmith/kafka_webscraper_logger
    environment:
      WEBSCRAPER_CONFIG: "/config/config.json"
    volumes: 
      - ./config:/config



