
version: '3.4'

services:
      
  #producer:
    #image: blakeasmith/kafka_webscraper_producer
    #environment:
            #WEBSCRAPER_BOOTSTRAPS: "35.217.96.115:9092"
            #DELAY_BETWEEN_JOBS: "1000"
            #WEBSCRAPER_DEBUG: "false"
    #logging:
      #driver: none

  #provider: 
    #image: blakeasmith/kafka_webscraper_provider
    #environment:
      #WEBSCRAPER_BOOTSTRAPS: "35.217.96.115:9092"
    #command: "--jars plugins --services services/services.json"
    #volumes: 
      #- ./plugins:/plugins
      #- ./services:/services

  #proxy:
    #image: blakeasmith/webscraper_proxy_server
    #ports:
        #- "8080:8080"
    #environment:
      #WEBSCRAPER_BOOTSTRAPS: "35.217.96.115:9092"

  #proxyclient:
    #image: blakeasmith/webscraper_proxy_client
    #environment:
        #PROXY_SERVER: "http://35.209.173.94:8080"

  client:
    image: blakeasmith/kafka_webscraper_client
    environment:
      WEBSCRAPER_BOOTSTRAPS: "35.217.96.115:9092"
        
  wordcount_reducer:
    image: blakeasmith/webscraper_reducer_wordcount
    environment:
      WEBSCRAPER_BOOTSTRAPS: "35.217.96.115:9092"
    volumes:
        - ./logs:/logs

